# Generated by Django 6.0.2 on 2026-02-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB, recommended: 400x400px)',
                                    null=True, upload_to='profile_pictures/'),
        ),
    ]
