# Generated by Django 6.0.2 on 2026-02-03 18:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB, recommended: 400x400px)',
                                    null=True, upload_to=users.models.profile_picture_upload_path),
        ),
    ]
