# Generated by Django 6.0.1 on 2026-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencerequest',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inferencerequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
