# Generated by Django 6.0.2 on 2026-02-06 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("version", models.CharField(max_length=20)),
                ("domain", models.CharField(max_length=50)),
                ("detection_type", models.CharField(max_length=50)),
                (
                    "input_shape",
                    models.JSONField(
                        help_text="Expected input shape [height, width, channels]"
                    ),
                ),
                ("num_classes", models.PositiveIntegerField()),
                ("class_labels", models.JSONField(help_text="List of class labels")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "detection_type"],
                        name="ml_mlmodel_domain_9529e5_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="ml_mlmodel_is_acti_69a790_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InferenceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detection_type", models.CharField(max_length=50)),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("request_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        help_text="Processing time in milliseconds"
                    ),
                ),
                (
                    "image_hash",
                    models.CharField(
                        help_text="SHA256 hash of input image", max_length=64
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ml.mlmodel"
                    ),
                ),
            ],
            options={
                "ordering": ["-request_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["model", "request_timestamp"],
                        name="ml_inferenc_model_i_414a6c_idx",
                    ),
                    models.Index(
                        fields=["detection_type"], name="ml_inferenc_detecti_5ef760_idx"
                    ),
                ],
            },
        ),
    ]
