name: NeuroLens CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  backend:
    name: Backend Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: envs/neurolens-api.yml
      - run: python -m compileall backend

  ml:
    name: ML Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: envs/neurolens-ml.yml
      - run: python -m compileall ml

  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          cd frontend
          npm install
          npm run build
